project:
  type: website

website:
  title: "packages.tesselle"

  site-url: https://www.tesselle.org
  repo-url: https://github.com/tesselle/packages
  repo-actions: [edit, issue]

  favicon: /images/icons/favicon.ico
  image: /images/card.png

  search: false
  navbar:
    pinned: true
    right:
      - icon: house
        text: Homepage
        href: "https://www.tesselle.org"
      - icon: github
        text: Github
        href: https://github.com/tesselle/
      - icon: download
        text: R-universe
        href: https://tesselle.r-universe.dev/

  page-footer:
    center: |
      <a href="https://www.u-bordeaux-montainge.fr"><img src="https://www.tesselle.org/images/logo-ubm.svg" class="logo-institution" /></a><a href="https://www.cnrs.fr"><img src="https://www.tesselle.org/images/logo-cnrs.svg" class="logo-institution" /></a>

      The tesselle project is supported by <a href="https://www.archeosciences-bordeaux.fr/" target="_blank">Archéosciences Bordeaux</a>, the <a href="https://mshs.univ-toulouse.fr/" target="_blank"><abbr title="Centre de Recherche et d'Études pour l'Art Préhistorique">CREAP</abbr></a> and the <a href="https://www.huma-num.fr/" target="_blank"><abbr title="Très Grande Infrastructure de Recherche">TGIR</abbr> Huma-Num</a>.
      <noscript><p><img src="https://analyseweb.huma-num.fr/matomo.php?idsite=332&rec=1" style="border:0" alt="" /></p></noscript>

format:
  html:
    include-in-header: _header.html

theme:
  - custom.scss
